fix packages script

diff --git a/bin/setup/packages b/bin/setup/packages
--- a/bin/setup/packages
+++ b/bin/setup/packages
@@ -2,15 +2,15 @@
 
 # TODO add --upgrade flag
 
-if uname != "Darwin"; then exit 1
+if uname != "Darwin"; then exit 1; fi
 
 eval "export HOMEBREW_NO_ANALYTICS=1"
 eval "export HOMEBREW_NO_INSECURE_REDIRECT=1"
 eval "export HOMEBREW_CASK_OPTS=--require-sha"
 
 if ! command -v brew &> /dev/null; then
-    echo "homebrew not found, brew_installing homebrew."
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    echo "homebrew not found, installing homebrew."
+    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
     eval "$(/opt/homebrew/bin/brew shellenv)"
     exit 1
 fi
